# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


House.destroy_all
Character.destroy_all

stark = House.create!(name: "Stark", family_crest_url: "http://unrealitymag.com/wp-content/uploads/2011/09/thrones1.jpg",realm: "North", history: "Seated in Winterfell, House Stark is the principle house of the northern lands of Westeros. House Stark ruled as Kings in the North for thousands of years before the Targaryens came to power and conquered the Seven Kingdoms. The Starks were then made Lords of Winterfell and Wardens of the North. Its motto is “Winter Is Coming,” and its coat of arms is a gray direwolf on a white background. House Stark is known for its honorable devotion to duty.")
lannister = House.create!(name: "Lannister", family_crest_url: "https://s-media-cache-ak0.pinimg.com/564x/d0/b2/c1/d0b2c1070a34ff44acf356b86bb6be64.jpg", realm: "Westerlands", history: "House Lannister is seated at Casterly Rock in the Westerlands, where it ruled the West until the Targaryens invaded and conquered the Seven Kingdoms. The Lannisters were made Wardens of the West afterward. The Lannisters are the richest family in Westeros because of the gold mines located on their lands. Tywin Lannister, head of the house, served as Hand of the King under King Aerys II Targaryen, until Robert Baratheon deposed the Targaryens. House Lannister’s coat of arms is a gold lion on a red background, and its motto is “Hear Me Roar!”")
targaryen = House.create!(name: "Targaryen", family_crest_url: "https://s-media-cache-ak0.pinimg.com/564x/11/c9/bf/11c9bfc4b4026071368765addad6de6f.jpg", realm: "scattered", history: "Originally from Valyria on the continent of Essos, House Targaryen conquered the Seven Kingdoms of Westeros and ruled for 300 years through the use of dragons. Its coat of arms is a red three-headed dragon on black, and its motto is “Fire and Blood.” The rule of the Targaryens ended when Robert Baratheon and Ned Stark led a rebellion to depose King Aerys, during which the king was slain by Jaime Lannister. Afterward, Robert took the Iron Throne, and Aerys’s surviving two children (Daenerys and Viserys) were exiled to Essos.")
baratheon = House.create!(name: "Baratheon", family_crest_url: "https://s-media-cache-ak0.pinimg.com/236x/e5/b4/08/e5b4080afb52b6250c7287318987dfec.jpg", realm: "King's Landing", history: "House Baratheon is the principle house of the Stormlands and is the youngest of the noble houses. King Robert is head of the house, though he lives in King’s Landing. The official seat of the house is in Storm’s End, and the youngest of the Baratheon brothers, Renly, is Lord of Storm’s End. The middle Baratheon brother, Stannis, is Lord of Dragonstone, which is a secondary seat for the house. House Baratheon’s coat of arms is a black stag on a bright yellow background, and its motto is “Ours Is the Fury.”")
greyjoy = House.create!(name: "Greyjoy", family_crest_url: "https://s-media-cache-ak0.pinimg.com/236x/16/07/a6/1607a64f294bbf73290f0962dc0398b2.jpg", realm: "Westeros", history: "Seated in Pyke in the Iron Islands, House Greyjoy became Lords Paramount of the Iron Islands after the Targaryens conquered Westeros. Ten years before Game of Thrones begins, Lord Balon Greyjoy led a failed rebellion against King Robert, after which Lord Balon had to give his youngest son, Theon, to the Starks as a hostage to live in Winterfell in order to retain control of the Iron Islands. House Greyjoy’s coat of arms is a golden kraken on black, and its motto is “We Do Not Sow.”")
arryn = House.create!(name: "Arryn", family_crest_url: "https://s-media-cache-ak0.pinimg.com/236x/52/80/65/528065918c3a6c9c9c1ae72e13e1ae77.jpg", realm: "Vale", history: "House Arryn is the principle house in the Vale and is seated in a small castle called the Eyrie, which is located at the top of a mountain. Jon Arryn, the head of the house, served King Robert as Hand of the King; Jon was poisoned shortly before Game of Thrones begins, which prompts Robert to ask Ned Stark to become Hand of the King. Now, Jon’s only son Robert is Lord of the Eyrie, with his mother Lysa acting as regent. House Arryn’s coat of arms is white moon and falcon on blue, and its motto is “As High as Honor.”")
martell = House.create!(name: "Martell", family_crest_url: "https://s-media-cache-ak0.pinimg.com/236x/4a/8e/76/4a8e76ea93f0555fa342b44f31369b11.jpg", realm: "Dorne", history: "Seated at Sunspear Castle in Dorne, House Martell resisted conquest by the Targaryens and was allowed to remain sovereign; in fact, Dorne was the only kingdom that maintained its independence during the Targaryen conquest. House Martell supported the Targaryens during Robert Baratheon’s rebellion, but ended up swearing fealty to Robert after he took the Iron Throne. House Martell isolated itself from the other houses because of their anger and resentment of the Lannisters. Its coat of arms is a gold spear piercing a red sun on a gold background, and its motto is “Unbowed, Unbent, Unbroken.”")
tully = House.create!(name: "Tully", family_crest_url: "https://s-media-cache-ak0.pinimg.com/236x/08/f5/e7/08f5e7ec32d6d9094b1bbb9fad8e2ba0.jpg", realm: "Riverlands", history: "House Tully is seated at Riverrun in the Riverlands. Catelyn Stark and Lysa Arryn are the daughters of Hoster Tully, the Lord of Riverrun. House Tully’s coat of arms is a silver trout on blue and red stripes, and its motto is “Family, Duty, Honor.”")
tyrell = House.create!(name: "Tyrell", family_crest_url: "https://s-media-cache-ak0.pinimg.com/564x/df/51/b4/df51b4c7e7bc1a0c1c5e39df5d349e20.jpg", realm: "Highgarden", history: "House Tyrell is the principle house in the Reach and is seated in Highgarden. The Targaryens made the Tyrells Lords of Highgarden after the king of the Reach was killed. The women of House Tyrell are known to be clever leaders, which is apparent in Margaery Tyrell’s rise to become Renly Baratheon’s wife, then betrothed to Joffrey after Renly’s death. House Tyrell’s coat of arms is a golden rose on a green background, and its motto is “Growing Strong.”")

Character.create!(name: "Eddard(Ned) Stark",photo_url: "http://vignette1.wikia.nocookie.net/gameofthrones/images/3/37/Eddard_Stark_infobox_new.jpg/revision/latest?cb=20160730050722", bio: "Eddard (Ned) Stark (Patriarch, Lord of Winterfell, Warden of the North)", house_id: stark.id )
Character.create!(name: "Catelyn Stark",photo_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/d/d8/CatelynS3Promo.jpg/revision/latest?cb=20131004004734", bio: "Ned's wife", house_id: stark.id)
Character.create!(name: "Robb Stark",photo_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/5/50/S3E9_Robb_Stark_main.jpg/revision/latest/scale-to-width-down/653?cb=20160718071203", bio: "Ned and Catelyn’s oldest son, heir to Winterfell", house_id: stark.id )
Character.create!(name: "Tywin Lannister",photo_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/7/71/Tywin_Lannister_4x08.jpg/revision/latest/scale-to-width-down/699?cb=20161215024806", bio: "Patriarch, Lord of Casterly Rock, Warden of the West", house_id: lannister.id)
Character.create!(name: "Robert Baratheon",photo_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/d/d4/RobertBaratheon.jpg/revision/latest?cb=20141119000127", bio: "Patriarch, King of the Seven Kingdoms", house_id: baratheon.id )
